[package]
name = "billon_row_challenge"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true

[dependencies]
divan = "0.1.14"
rustc-hash = "2.0.0"

[[bench]]
name = "example"
harness = false
